# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e96dba9131b7e7d8d9d2a6c29dfe31e5d9edaf2becdd45cedfa97c07b34886750994250d73c4e9debd4ccf023761719c2541265a655c640f641414510dd97d

test:
  secret_key_base: fc039b370b91843eb82455bd8339e9759d624bde295e2c6d6636d9611a82488ae41f54701e28c90804c530a7b06d4e0b5a6aca9c7f1aa47206ba8c98ba8252e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
